export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const APPLE_SIGNUP_REQUEST = 'APPLE_SIGNUP_REQUEST';
export const APPLE_SIGNUP_SUCCESS = 'APPLE_SIGNUP_SUCCESS';
export const APPLE_SIGNUP_ERROR = 'APPLE_SIGNUP_ERROR';

export const SPOTIFY_AUTH_REQUEST = 'SPOTIFY_AUTH_REQUEST';
export const SPOTIFY_AUTH_SUCCESS = 'SPOTIFY_AUTH_SUCCESS';
export const SPOTIFY_AUTH_ERROR = 'SPOTIFY_AUTH_ERROR';

export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';

export const RESEND_VERIFY_EMAIL_REQUEST = 'RESEND_VERIFY_EMAIL_REQUEST';
export const RESEND_VERIFY_EMAIL_SUCCESS = 'RESEND_VVERIFY_EMAIL_SUCCESS';
export const RESEND_VERIFY_EMAIL_ERROR = 'RESEND_VVERIFY_EMAIL_ERROR';

export const FORGOT_PWD_REQUEST = 'FORGOT_PWD_REQUEST';
export const FORGOT_PWD_SUCCESS = 'FORGOT_PWD_SUCCESS';
export const FORGOT_PWD_ERROR = 'FORGOT_PWD_ERROR';

export const RESET_PWD_REQUEST = 'RESET_PWD_REQUEST';
export const RESET_PWD_SUCCESS = 'RESET_PWD_SUCCESS';
export const RESET_PWD_ERROR = 'RESET_PWD_ERROR';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR';

export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_ERROR = 'UPDATE_ADDRESS_ERROR';

export const SYNC_SPOTIFY_DATA_REQUEST = 'SYNC_SPOTIFY_DATA_REQUEST';
export const SYNC_SPOTIFY_DATA_SUCCESS = 'SYNC_SPOTIFY_DATA_SUCCESS';
export const SYNC_SPOTIFY_DATA_FAILURE = 'SYNC_SPOTIFY_DATA_FAILURE';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';

export const USER_BADGE_REQUEST = 'USER_BADGE_REQUEST';
export const USER_BADGE_SUCCESS = 'USER_BADGE_SUCCESS';
export const USER_BADGE_FAILURE = 'USER_BADGE_FAILURE';

export const USER_SAVED_OFFERS_REQUEST = 'USER_SAVED_OFFERS_REQUEST';
export const USER_SAVED_OFFERS_SUCCESS = 'USER_SAVED_OFFERS_SUCCESS';
export const USER_SAVED_OFFERS_FAILURE = 'USER_SAVED_OFFERS_FAILURE';

export const UPLOAD_USER_PROFILE_REQUEST = 'UPLOAD_USER_PROFILE_REQUEST';
export const UPLOAD_USER_PROFILE_SUCCESS = 'UPLOAD_USER_PROFILE_SUCCESS';
export const UPLOAD_USER_PROFILE_ERROR = 'UPLOAD_USER_PROFILE_ERROR';

export const USER_ACCEPTED_TERMS_SERVICES_REQUEST = 'USER_ACCEPTED_TERMS_SERVICES_REQUEST';
export const USER_ACCEPTED_TERMS_SERVICES_SUCCESS = 'USER_ACCEPTED_TERMS_SERVICES_SUCCESS';
export const USER_ACCEPTED_TERMS_SERVICES_ERROR = 'USER_ACCEPTED_TERMS_SERVICES_ERROR';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_ERROR = 'USER_DELETE_ERROR';

export const LOG_OUT = 'LOG_OUT';
export const SET_USER_INFO = 'SET_USER_INFO';

export interface IAuthAttribute {
    name: string;
    email: string;
    date_time: string;
    type: any;
}
